name: Continuous Integration

on: [pull_request]

env:
  NODE_VERSION: 20

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run format:check
      - run: npm test --coverage
      # sonarcloud scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TEST_COVERAGE }}
        with:
          args: >
            -Dsonar.projectKey=bitvavo_frontend-website # SonarCloud project
            -Dsonar.organization=bitvavo # SonarCloud organization (always bitvavo)
            -Dsonar.sources=src # source of the project
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/e2e/**,**/cypress/**,**/github-trigger/** # exclusion repository
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info # coverage file
            -Dsonar.typescript.tsconfigPath=tsconfig.json # typescript specific config, this file is in the repo
            -Dsonar.sourceEncoding=UTF-8
