name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        required: true

env:
  node_version: 20

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest-4core
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.release_token }}

      - name: Set author in Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}

      - run: npm ci

      - name: Bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push release commit
        run: git push --tags origin ${{ github.ref_name }}

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          draft: true
